# name: Build and Push Image

# on: [push]

# jobs:
#   build:
#     environment:
#       name: Build image
    
#     runs-on: ubuntu-latest
    
#     steps:
#       - name: Pull git repo
#         uses: actions/checkout@v2
#         with:
#           submodules: recursive

#       - name: Configure AWS Credentials
#         uses: aws-actions/configure-aws-credentials@v1
#         with:
#           aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
#           aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#           aws-region: us-east-1

#       - name: Build container
#         run: |
#           docker build --build-arg AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }} \
#                       --build-arg AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }} \
#                       --tag dltb-containr:lambda-0.1 .
      
#       - name: Push2ECR
#         id: ecr
#         uses: jwalton/gh-ecr-push@v1
#         with:
#           access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
#           secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#           region: us-east-1
#           image: dltb-containr:lambda-0.1

#       - name: Update lambda with image
#         run: aws lambda update-function-code --function-name inference --image-uri ${{ secrets.ECR }}/dltb-containr:lambda-0.3